travis:
  secure:
    BINSTAR_TOKEN: kbvPxMzGZPHzDBIL44WF7gWEkHePQbWnlY6Kvg6FdD0JF9F/E1JOf12C19o+5RPrjqojVESy1gHFI+we7lWG+lrbXPXtOrCy6VoVs5U28E4NZ2I+xMUpfcy57z2uztIZh5jtgS09NknFnmAn5IO7nsCt9B4V9cKJZ37LAGxv79J3BO8lXPyt6PpRFEFsL3PK87VWlIFtFhaMgljHfF5V/LpzyEepGhf16RYZK8Z/Ag1O4KZkFrcMljjDiPpx3okPJ8zIquCCm7L6M6KjrKFmVD+xyoBeT9klH+eNBRW3bdj/jmZhAyoA+xvcUfmS/rFkD4RZys9CkzpHevc+RW6wq8YtGuopFgM4zSb6rw1ulMQoxuNqSR5xm93NQc8wTwXyz4Z0UOTVFbWiJVG9vFfdWo7dp1hdhFrpLBaUASlzrQkm11WKTPDsU39jlgTEcN6ZMeWCrjxlJkUIXBf3rssKsdIlF6lpVb1Ar8rLv2JptkfeOnw7VHscCDh4OUVAD/c/aaqCpgVHJEhHmSVPnTR5FB3iVlzmnBReCmJEZ67J3JbFmh5/U661in0n+SJm5YjlrBKtz8F46Z9j44Y+xxK8nTkqETcTKyT1SwBc4fldIhQgGgvDFAqGXGDXsLm3PvWNimRP6XayUpRrQQfkr/W7IVcp3lIIleH+SflpTgRUUbg=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
